## Problem 2: Create buffers around shopping centers (3 points)

Let’s continue with our case study and calculate a 1.5 km buffer around the geocoded points.

### a) Load the shopping centre data set (1 point)

First, load the shopping centre *point* data set you created in *problem 1* into a `GeoDataFrame` called `shopping_centres`.

In [1]:
import geopandas as gpd
import pathlib
DATA_DIRECTORY = pathlib.Path().resolve()

shopping_centres = gpd.read_file(filename=DATA_DIRECTORY / "shopping_centres.gpkg")
shopping_centres

,address,id,name,addr,geometry
0,"Kingsmead Road, The King's Mile, Canterbury, K...",0,SAINSBURY CANTERBURY,"KINGSMEAD ROAD,CANTERBURY,CT1 1BW",POINT (23843402.685 5960802.961)
1,None,1,SAINSBUR FOLKSTONE,"SAINSBURY J,WELLINGTON ROAD,CT20 2RX",POINT EMPTY
2,None,2,SAINSBURY PARK FARM,"PARK FARM ESTATE,FOLKESTONE,CT19 5GA",POINT EMPTY
3,"Sainsbury's, Dadson Way, Northwood, Ramsgate, ...",3,SAINSBURY THANET,"SAINSBURY WESTWOOD,RAMSGATE,CT10 2QG",POINT (23867190.796 5961274.874)
4,"Simone Weil Avenue, Repton Park South, Repton ...",4,SAINSBURY BYBROOK AS,"SIMONE WEIL AVENUE,ASHFORD,TN24 8YN",POINT (23823730.264 5952005.805)
...,...,...,...,...,...
525,None,525,SAINSBURY 2663 WALTON ON,"NEW ZELAND AVENUE,SURREY,KT12 1AD",POINT EMPTY
526,None,526,SAINSBURY 2053 SURY BASIN,"SURREY BASIN,SURREY,KT2 5EN",POINT EMPTY
527,"Sainsbury's Local, 68-78, High Street, Hampton...",527,SAINSBURY 4821 HAMPTON HI,"68-78 HIGH STREET,HAMPTON,TW12 1NY",POINT (23751040.836 6011165.982)
528,"Windermere Drive, Lyppard Grange, Blackpole, W...",528,SAINSBURY 53 BLACKPOLE,"WINDERMERE DRIVE,WORCESTER,WR4 9JN",POINT (23660868.068 6143481.569)
529,None,529,SAINSBURY 2219 ST JOHNS (,"WORCESTER ST JOHNS,WORCESTER,WR2 4EL",POINT EMPTY


---

### b) Create a *buffer* around the points (1 points)

Calculate a 1.5 km buffer for each geocoded point. Overwrite the `geometry` column with the new buffer geometry.

Use the [`geopandas.GeoDataFrame.buffer()` method](http://geopandas.org/geometric_manipulations.html#GeoSeries.buffer), that uses shapely’s [`buffer()`](http://toblerity.org/shapely/manual.html#object.buffer) in the background. You only need to care about the `distance` parameter, don’t worry about the possible other arguments.

In [13]:
shopping_centres['buffer'] = shopping_centres.geometry.buffer(1500)
shopping_centres=shopping_centres.set_geometry("buffer", drop=False)
shopping_centres = shopping_centres[['id', 'name', 'addr', 'address', 'buffer']]
shopping_centres

/var/folders/0l/3j89s50s0jbbj84m6sbcbtgw0000gn/T/ipykernel_36642/1683083982.py:2: FutureWarning: The `drop` keyword argument is deprecated and in future the only supported behaviour will match drop=False. To silence this warning and adopt the future behaviour, stop providing `drop` as a keyword to `set_geometry`. To replicate the `drop=True` behaviour you should update your code to
`geo_col_name = gdf.active_geometry_name; gdf.set_geometry(new_geo_col).drop(columns=geo_col_name).rename_geometry(geo_col_name)`.
  shopping_centres=shopping_centres.set_geometry("buffer", drop=False)

,id,name,addr,address,buffer
0,0,SAINSBURY CANTERBURY,"KINGSMEAD ROAD,CANTERBURY,CT1 1BW","Kingsmead Road, The King's Mile, Canterbury, K...","POLYGON ((23847899.071 5960950.164, 23847900.8..."
1,1,SAINSBUR FOLKSTONE,"SAINSBURY J,WELLINGTON ROAD,CT20 2RX",None,POLYGON EMPTY
2,2,SAINSBURY PARK FARM,"PARK FARM ESTATE,FOLKESTONE,CT19 5GA",None,POLYGON EMPTY
3,3,SAINSBURY THANET,"SAINSBURY WESTWOOD,RAMSGATE,CT10 2QG","Sainsbury's, Dadson Way, Northwood, Ramsgate, ...","POLYGON ((23871687.183 5961422.077, 23871688.9..."
4,4,SAINSBURY BYBROOK AS,"SIMONE WEIL AVENUE,ASHFORD,TN24 8YN","Simone Weil Avenue, Repton Park South, Repton ...","POLYGON ((23828226.65 5952153.008, 23828228.45..."
...,...,...,...,...,...
525,525,SAINSBURY 2663 WALTON ON,"NEW ZELAND AVENUE,SURREY,KT12 1AD",None,POLYGON EMPTY
526,526,SAINSBURY 2053 SURY BASIN,"SURREY BASIN,SURREY,KT2 5EN",None,POLYGON EMPTY
527,527,SAINSBURY 4821 HAMPTON HI,"68-78 HIGH STREET,HAMPTON,TW12 1NY","Sainsbury's Local, 68-78, High Street, Hampton...","POLYGON ((23755537.222 6011313.185, 23755539.0..."
528,528,SAINSBURY 53 BLACKPOLE,"WINDERMERE DRIVE,WORCESTER,WR4 9JN","Windermere Drive, Lyppard Grange, Blackpole, W...","POLYGON ((23665364.454 6143628.773, 23665366.2..."
529,529,SAINSBURY 2219 ST JOHNS (,"WORCESTER ST JOHNS,WORCESTER,WR2 4EL",None,POLYGON EMPTY

In [12]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION
assert shopping_centres.geometry.geom_type.unique() == ["Polygon"]


---

### d) Save buffer geometry layer (1 point)

Save the data frame containing the buffer geometries into a new layer `buffers` inside the same *GeoPackage* `shopping_centres.gpkg`:

In [14]:
shopping_centres.to_file('shopping_centres.gpkg', layer='buffers')